seed_everything: 2023
mode: train
data_name: &data_name mnist
diffusion_type: &diffusion_type sde
discrete: &discrete False
load_train: False
ckpt_path: None

trainer:
  log_every_n_steps: 5
  check_val_every_n_epoch: 5
  num_sanity_val_steps: 0
  logger:
      class_path: TensorBoardLogger
      init_args:
        save_dir: ./checkpoint/
        name: *diffusion_type
        version: *data_name
        default_hp_metric: False
  accelerator: gpu
  devices:
    - 0
  max_epochs: 1000
  callbacks+:
    - class_path: ModelCheckpoint
      init_args:
        monitor: train_loss
        mode: min
        save_last: True

model:
  class_path: trainer.DiffusionModule
  init_args:
    diffusion_type: *diffusion_type
    data_name: *data_name
    discrete: *discrete
    total_steps: 250
    lr: 2.5e-4
    sde_type: "subVP"

data:
  class_path: trainer.DiffusionDataModule
  init_args:
    data_name: *data_name
    discrete: *discrete
    batch_size: 256
    test_batch_size: 64
    num_workers: 16